Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TSI.DAL;
using TSI.Models;

namespace TSI.Controllers
{
	public class AdminController : Controller
	{
		public IActionResult CarPanel()
		{
			var context = new DataContext();

			ViewBag.Cars = context.Cars;
			return View();
		}

		public IActionResult OfficePanel()
		{
			var context = new DataContext();

			ViewBag.Offices = context.Offices;
			return View();
		}

		public IActionResult OrderPanel()
		{
			var context = new DataContext();

			Dictionary<Order,List<string>> connections = new Dictionary<Order,List<string>>();
			var orders = context.Orders.ToList();

			foreach (var order in orders)
			{
				var connectors = context.CarsOrdersConnectors.Where(conn => conn.OrderId == order.OrderId).ToList();

				List<string> list = new List<string>();
				foreach (var connector in connectors)
				{
					var carName = context.Cars.FirstOrDefault(car => car.CarId == connector.CarId).Mark;
					list.Add(carName);
				}

				connections.Add(order, list);
			}

			ViewBag.Orders = connections;

			return View();
		}

		public IActionResult OnDeleteCar(Guid id)
		{
			var context = new DataContext();
			context.Cars.Remove(context.Cars.FirstOrDefault(car => car.CarId == id));
			context.SaveChanges();

			return View("CarPanel");
		}

		public IActionResult OnDeleteOffice(Guid id)
		{
			var context = new DataContext();
			context.Offices.Remove(context.Offices.FirstOrDefault(office => office.OfficeId == id));
			context.SaveChanges();

			return View("OfficePanel");
		}

		public IActionResult OnDeleteOrder(Guid id)
		{
			var context = new DataContext();
			context.Orders.Remove(context.Orders.FirstOrDefault(order => order.OrderId == id));
			context.SaveChanges();

			return View("OrderPanel");
		}

		public static string GetName(Guid userId)
		{
			var context = new DataContext();
			return context.Users.FirstOrDefault(user => user.UserId == userId).Name;
		}

		public static string GetAddress(Guid officeId)
		{
			var context = new DataContext();
			return context.Offices.FirstOrDefault(office => office.OfficeId == officeId).FullAddress;
		}

		[HttpGet]
		public string GetOfficePanel()
		{
			var context = new DataContext();

			var offices = context.Offices
				.Select(office => new OfficeResponse { City = office.City, Street = office.Street, Building = office.Building })
				.ToList();

			return JsonConvert.SerializeObject(offices);
		}
	}
}

Controllers/CarsController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TSI.DAL;
using TSI.Helpers;
using TSI.Models;

namespace TSI.Controllers
{
	public class CarsController : Controller
	{
		public IActionResult AddCar()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> AddCar(Car car, IFormFile imageData)
		{
			var context = new DataContext();

			car.Photo = await ImageHelper.UploadImage(imageData);

			context.Cars.Add(car);
			context.SaveChanges();
			return Redirect("/Admin/CarPanel");
		}

		public IActionResult UpdateCar(Guid id)
		{
			var context = new DataContext();
			var car = context.Cars.FirstOrDefault(car => car.CarId == id);
			ViewBag.Car = car;

			return View();
		}

		[HttpPost]
		public IActionResult UpdateCar(Car carData, Guid id)
		{
			var context = new DataContext();
			var car = context.Cars.FirstOrDefault(car => car.CarId == id);
			car.BodyType = carData.BodyType;
			car.Consumption = carData.Consumption;
			car.Drive = carData.Drive;
			car.Engine = carData.Engine;
			car.Gears = carData.Gears;
			car.Mark = carData.Mark;
			car.Mileage = carData.Mileage;
			car.Power = carData.Power;
			car.State = carData.State;
			car.Price = carData.Price;
			car.Transmission = carData.Transmission;
			car.Year = carData.Year;
			context.Cars.Update(car);
			context.SaveChanges();

			return Redirect("/Admin/CarPanel");
		}


		public IActionResult CarPage(Guid id)
		{
			var context = new DataContext();
			var car = context.Cars
				.FirstOrDefault(car => car.CarId == id);

			ViewBag.Title = car.Mark;
			ViewBag.Img = Url.Content(ImageHelper.GetUrl(car.Photo));

			ViewBag.Car = car;
			return View();
		}




	}
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TSI.DAL;
using TSI.Models;

namespace TSI.Controllers
{
	public class OrderController : Controller
	{
		public IActionResult Order()
		{
			var context = new DataContext();
			var cartItems = context.CartItems
				.OrderByDescending(cartItem => cartItem.Price)
				.ToList();
			ViewBag.Offices = context.Offices;

			if (!cartItems.Any())
			{
				ViewBag.CartItems = new List<CartItem>();
				ViewBag.Total = 0;
			}
			else
			{
				ViewBag.CartItems = cartItems;
				ViewBag.Total = cartItems.Sum(item => item.Price);
			}
			return View();
		}

		public IActionResult AddToOrder(Guid id)
		{
			var context = new DataContext();
			var car = context.Cars
				.FirstOrDefault(car => car.CarId == id);

			var cartItem = new CartItem();
			cartItem.CartItemId = Guid.NewGuid();
			cartItem.Mark = car.Mark;
			cartItem.Year = car.Year;
			cartItem.Transmission = car.Transmission;
			cartItem.Gears = car.Gears;
			cartItem.Price = car.Price;
			cartItem.Power = car.Power;
			cartItem.Photo = car.Photo;
			cartItem.CarId = id;

			context.CartItems.Add(cartItem);
			context.SaveChanges();


			return Redirect("/Order/Order");
		}

		public IActionResult AddOrder(OrderViewModel orderView)
		{
			var context = new DataContext();
			var cartItems = context.CartItems.ToList();
			var office = context.Offices.FirstOrDefault(off => off.FullAddress == orderView.Office).OfficeId;

			var order = new Order();
			order.OrderId = Guid.NewGuid();
			if (context.Users.FirstOrDefault(user => user.Name == HttpContext.User.Identity.Name) != null)
			{
				order.UserId = context.Users.FirstOrDefault(user => user.Name == HttpContext.User.Identity.Name).UserId;
			}
			else
			{
				order.UserId = new Guid("d8c9ea9b-c836-4dde-8664-586eaa5d2c6e");
			}
			
			order.CreateDate = DateTime.Now;
			order.Total = cartItems.Sum(item => item.Price);
			order.Status = "Заказ принят";
			order.OfficeId = office;

			context.Orders.Add(order);

			foreach (var item in cartItems)
			{
				var connector = new CarsOrdersConnector();
				connector.CarId = item.CarId;
				connector.OrderId = order.OrderId;
				connector.CarsOrdersConnectorId = Guid.NewGuid();

				context.CarsOrdersConnectors.Add(connector);
			}

			context.SaveChanges();

			context.CartItems.RemoveRange(context.CartItems);

			return Redirect("/Profile/Profile");
		}

		public IActionResult UpdateOrder(Guid id)
		{
			var context = new DataContext();
			var order = context.Orders.FirstOrDefault(order => order.OrderId == id);
			ViewBag.Order = order;

			return View();
		}

		[HttpPost]
		public IActionResult UpdateOrder(Order orderData, Guid id)
		{
			var context = new DataContext();
			var order = context.Orders.FirstOrDefault(order => order.OrderId == id);

			order.Status = order.Status;

			context.Orders.Update(order);
			context.SaveChanges();

			return Redirect("/Admin/OrderPanel");
		}
	}
}

Views/Admin/CarPanel.cshtml
@{
    ViewData["Title"] = "Панель администратора";
}

<main>
    <table>
        <thead>
        <tr>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>Марка</th>
            <th>Состояние</th>
            <th>Год производства</th>
            <th>Пробег</th>
            <th>Тип кузова</th>
            <th>Тип КПП</th>
            <th>Количество передач</th>
            <th>Тип двигателя</th>
            <th>Мощность</th>
            <th>Привод</th>
            <th>Расход</th>
            <th>Цена</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var row in ViewBag.Cars) {
            <tr>
                <td><a asp-controller="Cars" asp-action="UpdateCar" asp-route-id="@row.CarId">Редактировать</a></td>
                <td><a asp-controller="Admin" asp-action="OnDeleteCar" asp-route-id="@row.CarId">Удалить</a></td>
                <td>@row.Mark</td>
                <td>@row.State</td>
                <td>@row.Year</td>
                <td>@row.Mileage</td>
                <td>@row.BodyType</td>
                <td>@row.Transmission</td>
                <td>@row.Gears</td>
                <td>@row.Engine</td>
                <td>@row.Power</td>
                <td>@row.Drive</td>
                <td>@row.Consumption</td>
                <td>@row.Price</td>
            </tr>
        }
        </tbody>
    </table>
</main>

Views/Admin/OfficePanel.cshtml
@{
    ViewData["Title"] = "Панель администратора";
}

<script src="~/js/offices.js"></script>

<main style='padding: 10px'>
    <a onclick='showOffices()' class='btn btn-secondary'>Вывести все записи</a>
    <a asp-controller='Offices' asp-action='AddOffice' class='btn btn-secondary'>Перейти к добавлению записи</a>
    <table>
        <thead>
        <tr>
            <th>Город</th>
            <th>Улица</th>
            <th>Строение</th>
        </tr>
        </thead>
        <tbody id='officetbody'>
        </tbody>
    </table>
</main>

Views/Admin/OrderPanel.cshtml
@{
    ViewData["Title"] = "Панель администратора";
}



<main>
    <table>
        <thead>
        <tr>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>Пользователь</th>
            <th>Офис</th>
            <th>Дата</th>
            <th>Общая стоимость</th>
            <th>Статус</th>
            <th>Автомобили</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var row in ViewBag.Orders) {
            <tr>
                <td><a asp-controller="Order" asp-action="UpdateOrder" asp-route-id="@row.Key.OrderId">Обновить статус</a></td>
                <td><a asp-controller="Admin" asp-action="OnDeleteOrder" asp-route-id="@row.Key.OrderId">Удалить</a></td>
                <td>@TSI.Controllers.AdminController.GetName(row.Key.UserId)</td>
                <td>@TSI.Controllers.AdminController.GetAddress(row.Key.OfficeId)</td>
                <td>@row.Key.CreateDate</td>
                <td>@row.Key.Total</td>
                <td>@row.Key.Status</td>
                <td>@String.Join(", ",row.Value.ToArray())</td>
            </tr>
        }
        </tbody>
    </table>
</main>