Controllers/AboutController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TSI.DAL;

namespace TSI.Controllers
{
	public class AboutController : Controller
	{
		public IActionResult About()
		{
			var context = new DataContext();
			var offices = context.Offices.Select(office => office.FullAddress).ToList();

			ViewBag.Addresses = offices;

			return View();
		}
	}

}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TSI.DAL;
using TSI.Models;

namespace TSI.Controllers
{
	public class OrderController : Controller
	{
		public IActionResult Order()
		{
			var context = new DataContext();
			var cartItems = context.CartItems
				.OrderByDescending(cartItem => cartItem.Price)
				.ToList();
			ViewBag.Offices = context.Offices;

			if (!cartItems.Any())
			{
				ViewBag.CartItems = new List<CartItem>();
				ViewBag.Total = 0;
			}
			else
			{
				ViewBag.CartItems = cartItems;
				ViewBag.Total = cartItems.Sum(item => item.Price);
			}
			return View();
		}

		public IActionResult AddToOrder(Guid id)
		{
			var context = new DataContext();
			var car = context.Cars
				.FirstOrDefault(car => car.CarId == id);

			var cartItem = new CartItem();
			cartItem.CartItemId = Guid.NewGuid();
			cartItem.Mark = car.Mark;
			cartItem.Year = car.Year;
			cartItem.Transmission = car.Transmission;
			cartItem.Gears = car.Gears;
			cartItem.Price = car.Price;
			cartItem.Power = car.Power;
			cartItem.Photo = car.Photo;
			cartItem.CarId = id;

			context.CartItems.Add(cartItem);
			context.SaveChanges();


			return Redirect("/Order/Order");
		}

		public IActionResult AddOrder(OrderViewModel orderView)
		{
			var context = new DataContext();
			var cartItems = context.CartItems.ToList();
			var office = context.Offices.FirstOrDefault(off => off.FullAddress == orderView.Office).OfficeId;

			var order = new Order();
			order.OrderId = Guid.NewGuid();
			if (context.Users.FirstOrDefault(user => user.Name == HttpContext.User.Identity.Name) != null)
			{
				order.UserId = context.Users.FirstOrDefault(user => user.Name == HttpContext.User.Identity.Name).UserId;
			}
			else
			{
				order.UserId = new Guid("d8c9ea9b-c836-4dde-8664-586eaa5d2c6e");
			}
			
			order.CreateDate = DateTime.Now;
			order.Total = cartItems.Sum(item => item.Price);
			order.Status = "Заказ принят";
			order.OfficeId = office;

			context.Orders.Add(order);

			foreach (var item in cartItems)
			{
				var connector = new CarsOrdersConnector();
				connector.CarId = item.CarId;
				connector.OrderId = order.OrderId;
				connector.CarsOrdersConnectorId = Guid.NewGuid();

				context.CarsOrdersConnectors.Add(connector);
			}

			context.SaveChanges();

			context.CartItems.RemoveRange(context.CartItems);

			return Redirect("/Profile/Profile");
		}

		public IActionResult UpdateOrder(Guid id)
		{
			var context = new DataContext();
			var order = context.Orders.FirstOrDefault(order => order.OrderId == id);
			ViewBag.Order = order;

			return View();
		}

		[HttpPost]
		public IActionResult UpdateOrder(Order orderData, Guid id)
		{
			var context = new DataContext();
			var order = context.Orders.FirstOrDefault(order => order.OrderId == id);

			order.Status = order.Status;

			context.Orders.Update(order);
			context.SaveChanges();

			return Redirect("/Admin/OrderPanel");
		}
	}
}

Controllers/TermsController.cs
using Microsoft.AspNetCore.Mvc;

namespace TSI.Controllers
{
	public class TermsController : Controller
	{
		public IActionResult Terms()
		{
			return View();
		}
	}
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script src="~/js/jquery.js"></script>
    <script src="~/js/jquery.unobtrusive-ajax.js"></script>


</head>
<body>
<header>
    <div class="navigation">
        <ul>
            <li>
                <div class="logo">
                    <a asp-controller="Home" asp-action="Index">
                        <img src="~/img/logo.png" alt="Лого"/>
                    </a>
                </div>
            </li>
            <li class="navbuttons">
                <nav>
                    <a title="Как выбрать автомобиль" asp-controller="Advices" asp-action="Advices">Как выбрать автомобиль</a>
                    <div class="vertical-line"></div>
                    <a title="О нас" asp-controller="About" asp-action="About">О нас</a>
                    <div class="vertical-line"></div>
                    <a title="Условия покупки" asp-controller="Terms" asp-action="Terms">Условия покупки</a>
                    <div class="vertical-line"></div>
                    <a title="Оформление заказа" asp-controller="Order" asp-action="Order">Оформление заказа</a>
                    <div class="vertical-line"></div>
                    <a title="Личный кабинет" asp-controller="Profile" asp-action="Profile">Личный кабинет</a>
                </nav>
            </li>
        </ul>
    </div>
</header>
<div class="container">
    @RenderBody()
</div>
<footer>
    <div class="footer-info">
        <div class="main-office">
            <p>Адрес главного офиса:<br/>
                г. Самара<br/>
                ул. Льва Толстого<br/>
                д. 15 <br/>
                оф. 771</p>
        </div>
        <div class="contacts">
            <p>Телефон горячей линии:<br/>
                8-800-555-35-35</p>
            <p>Адрес электронной почты:<br/>
                superauto@superauto.com</p>
        </div>
    </div>
</footer>
</body>
</html>